# Generated by Django 2.2 on 2023-01-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Emailed',
        ),
    ]
