# Generated by Django 2.2 on 2023-01-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('recipient', models.CharField(max_length=300)),
            ],
        ),
    ]
