# Generated by Django 2.2 on 2023-01-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='booking_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
