# Generated by Django 2.2 on 2023-01-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0002_emailnotification_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
