# Generated by Django 2.2 on 2023-01-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0003_emailqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_service.EmailNotification'),
        ),
    ]
