# Generated by Django 2.2 on 2023-05-04 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('resource_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reset', models.BooleanField(default=False)),
                ('jira_issue_id', models.IntegerField(blank=True, null=True)),
                ('jira_issue_status', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(max_length=300)),
                ('ext_count', models.IntegerField(default=2)),
                ('project', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pdf', models.TextField(blank=True, default='')),
                ('idf', models.TextField(blank=True, default='')),
                ('complete', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Lab')),
                ('opnfv_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.OPNFVConfig')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_inventory.ResourceBundle')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
