# Generated by Django 2.2 on 2021-08-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20201109_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='jira_issue_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='jira_issue_status',
        ),
    ]
