# Generated by Django 2.2 on 2023-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='emailed_expiring',
            field=models.TextField(blank=True, default=True),
        ),
    ]
