# Generated by Django 2.2 on 2023-01-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_emailed_expiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='emailed_expiring',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
