# Generated by Django 2.2 on 2023-05-04 21:05

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(default=0)),
                ('location', models.TextField(default='unknown')),
                ('api_token', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=240)),
                ('lab_info_link', models.URLField(null=True)),
                ('project', models.CharField(default='LaaS', max_length=100)),
                ('lab_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VlanManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlans', models.TextField()),
                ('reserved_vlans', models.TextField()),
                ('block_size', models.IntegerField()),
                ('allow_overlapping', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('ssh_public_key', models.FileField(blank=True, null=True, upload_to=account.models.upload_to)),
                ('pgp_public_key', models.FileField(blank=True, null=True, upload_to=account.models.upload_to)),
                ('email_addr', models.CharField(default='email@mail.com', max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('oauth_token', models.CharField(max_length=1024)),
                ('oauth_secret', models.CharField(max_length=1024)),
                ('jira_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('booking_privledge', models.BooleanField(default=False)),
                ('public_user', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='PublicNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.IntegerField()),
                ('in_use', models.BooleanField(default=False)),
                ('cidr', models.CharField(default='0.0.0.0/0', max_length=50)),
                ('gateway', models.CharField(default='0.0.0.0', max_length=50)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Lab')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='vlan_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.VlanManager'),
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(default='This lab will be down for maintenance')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Lab')),
            ],
        ),
    ]
