# Generated by Django 2.2 on 2020-01-28 15:05

from django.db import migrations, models
import django.db.models.deletion


def pairObjects(apps, editor):
    Resource = apps.get_model("resource_inventory", "Resource")
    Host = apps.get_model("resource_inventory", "Host")
    ResourceBundle = apps.get_model("resource_inventory", "ResourceBundle")
    PhysicalNetwork = apps.get_model("resource_inventory", "PhysicalNetwork")
    for model in [Host, ResourceBundle, PhysicalNetwork]:
        for obj in model.objects.all():
            resource = Resource.objects.create()
            obj.resource_ptr = resource.pk
            obj.save()


def unpairObjects(apps, editor):
    Resource = apps.get_model("resource_inventory", "Resource")
    Host = apps.get_model("resource_inventory", "Host")
    ResourceBundle = apps.get_model("resource_inventory", "ResourceBundle")
    PhysicalNetwork = apps.get_model("resource_inventory", "PhysicalNetwork")
    for model in [Host, ResourceBundle, PhysicalNetwork]:
        for obj in model.objects.all():
            obj.resource_ptr = 0
            obj.save()
    Resource.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0012_auto_20200103_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        # Add temporary resource_ptr fields and populate it before adding
        migrations.AddField(
            model_name='host',
            name='resource_ptr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalnetwork',
            name='resource_ptr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcebundle',
            name='resource_ptr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(pairObjects, unpairObjects),
    ]
