# Generated by Django 2.2 on 2020-01-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0013_auto_20200128_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='id',
        ),
        migrations.RemoveField(
            model_name='physicalnetwork',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resourcebundle',
            name='id',
        ),
        migrations.AlterField(
            model_name='host',
            name='resource_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource_inventory.Resource'),
        ),
        migrations.AlterField(
            model_name='physicalnetwork',
            name='resource_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource_inventory.Resource'),
        ),
        migrations.AlterField(
            model_name='resourcebundle',
            name='resource_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resource_inventory.Resource'),
        ),
    ]
