# Generated by Django 2.2 on 2022-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0023_cloudinitfile_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
