# Generated by Django 2.2 on 2020-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    """TODO: set default resource_id fields."""

    dependencies = [
        ('api', '0010_auto_20191219_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosthardwarerelation',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostnetworkrelation',
            name='host',
        ),
        migrations.RemoveField(
            model_name='snapshotconfig',
            name='host',
        ),
        migrations.AddField(
            model_name='hosthardwarerelation',
            name='resource_id',
            field=models.CharField(default='default_id', max_length=200),
        ),
        migrations.AddField(
            model_name='hostnetworkrelation',
            name='resource_id',
            field=models.CharField(default='default_id', max_length=200),
        ),
        migrations.AddField(
            model_name='snapshotconfig',
            name='resource_id',
            field=models.CharField(default='default_id', max_length=200),
        ),
        migrations.AlterField(
            model_name='opnfvapiconfig',
            name='roles',
            field=models.ManyToManyField(to='resource_inventory.ResourceOPNFVConfig'),
        ),
    ]
