# Generated by Django 2.2 on 2020-02-18 15:36

from django.db import migrations, models


def set_resource_id(apps, schema_editor):
    for cls in ["HostHardwareConfig", "HostNetworkConfig", "SnapshotConfig"]:
        model = apps.get_model('api', cls)
        for m in model.objects.all():
            m.resource_id = m.host.labid
            m.save()


class Migration(migrations.Migration):
    """TODO: set default resource_id fields."""

    dependencies = [
        ('api', '0010_auto_20191219_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosthardwarerelation',
            name='resource_id',
            field=models.CharField(default='default_id', max_length=200),
        ),
        migrations.AddField(
            model_name='hostnetworkrelation',
            name='resource_id',
            field=models.CharField(default='default_id', max_length=200),
        ),
        migrations.AddField(
            model_name='snapshotconfig',
            name='resource_id',
            field=models.CharField(default='default_id', max_length=200),
        ),
        migrations.RunPython(set_resource_id),
        migrations.RemoveField(
            model_name='hosthardwarerelation',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostnetworkrelation',
            name='host',
        ),
        migrations.RemoveField(
            model_name='snapshotconfig',
            name='host',
        ),
        migrations.AlterField(
            model_name='opnfvapiconfig',
            name='roles',
            field=models.ManyToManyField(to='resource_inventory.ResourceOPNFVConfig'),
        ),
    ]
