# Generated by Django 2.2 on 2023-01-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210405_1943'),
        ('api', '0019_auto_20210907_1448'),
        ('api', '0022_add_cifile_generated_field'),
    ]

    operations = [
    ]
